import * as THREE from 'three';

export interface GameState {
  keys: Record<string, boolean>;
  playerDist: number;
  playerLane: number;
  speed: number;
  isDrifting: boolean;
  driftAngle: number;
  driftScore: number;
  nitro: number;
  isNosActive: boolean;
  timer: number;
  score: number;
  airborne: boolean;
  airHeight: number;
  airVelocityY: number;
  spinAngle: number;
  rollAngle: number;
  stuntScore: number;
  botDist: number;
  botLane: number;
  botSpeed: number;
  bot2Dist: number;
  bot2Lane: number;
  bot2Speed: number;
  bot3Dist: number;
  bot3Lane: number;
  bot3Speed: number;
  trafficCars: { mesh: THREE.Group; dist: number; lane: number; speed: number }[];
  drones: { mesh: THREE.Group; t: number; speed: number; lane: number; alt: number }[];
  landingCompression: number;
  cameraMode: 'chase' | 'far' | 'hood' | 'cockpit';
  trackLength: number;
  roadWidth: number;
  slipstreamActive: boolean;
  lastExhaustTime: number;
  crashCooldown: number;
  gear: number | string;
  rpm: number;
  steerAngle: number;
  steerYaw: number;
  steerRoll: number;
  steerPitch: number;
  collisionShake: number;
  gameOver: boolean;
  countdownActive: boolean;
  transmissionMode: 'auto' | 'manual';
  lightningActive: boolean;
  lightningTimer: number;
  suspensionOffset: number;
  suspensionVelocity: number;
}
